NAME = aveditor
DESC = FFmpeg video edit library
HEADERS = av_editor.h


OBJS = cmdutils.o                                     \
       ffmpeg.o                                         \
       opt_common.o

# Objects duplicated from other libraries for shared builds
SHLIBOBJS                    += log2_tab.o


TESTPROGS = aveditor
